# 1. Dataset Audit

## 1.1 Dataset Acquisition and Loading

In [106]:
from pathlib import Path
import numpy as np
import pandas as pd
import warnings

LABEL_COL = "Label"
warnings.filterwarnings('ignore')

PROJECT_DIR = "/Users/ashishkrsingh/Developers/Machine Learning/Projects/Network-Intrusion-Detection"
REPORT_DIR = Path(PROJECT_DIR) / "reports"

print("Import completed successfully")
print("Setup completed successfully")

Import completed successfully
Setup completed successfully

In [107]:
RAW_DATA_DIR = Path(PROJECT_DIR) / "data" / "raw"

datasets = []

for path in RAW_DATA_DIR.glob("*.csv"):
    try:
        df = pd.read_csv(path)
        df.columns = df.columns.str.strip()
        df["source_file"] = path.name.split('.')[0]
        print(f"Loaded {path.parts[-1]} ({path.stat().st_size / (1024 * 1024):.2f} MB)")
        datasets.append(df)

    except Exception as e:
        print(f"Error while loading {path.parts[-1]}: {e}")

print(f"Loaded {len(datasets)} datasets successfully")
DATASET = pd.concat(datasets, ignore_index=True)

print(f"\n{"="*25} Dataset Details: {"="*25}\n")
for df in datasets:
    print(f"{df['source_file'].iloc[0]}: {df.shape[0]} rows x {df.shape[1]} columns")

Loaded Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv (79.25 MB)
Loaded Monday-WorkingHours.pcap_ISCX.csv (168.73 MB)
Loaded Friday-WorkingHours-Morning.pcap_ISCX.csv (55.62 MB)
Loaded Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv (73.34 MB)
Loaded Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv (73.55 MB)
Loaded Tuesday-WorkingHours.pcap_ISCX.csv (128.82 MB)
Loaded Wednesday-workingHours.pcap_ISCX.csv (214.74 MB)
Loaded Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv (49.61 MB)
Loaded 8 datasets successfully

========================= Dataset Details: =========================

Thursday-WorkingHours-Afternoon-Infilteration: 288602 rows x 80 columns
Monday-WorkingHours: 529918 rows x 80 columns
Friday-WorkingHours-Morning: 191033 rows x 80 columns
Friday-WorkingHours-Afternoon-PortScan: 286467 rows x 80 columns
Friday-WorkingHours-Afternoon-DDos: 225745 rows x 80 columns
Tuesday-WorkingHours: 445909 rows x 80 columns
Wednesday-workingHours: 692703 rows x 80 columns
Thursday-WorkingHours-Morning-WebAttacks: 170366 rows x 80 columns

## 1.2 Dataset Structure and Composition

In [108]:
DATASET.sample(n = 10, random_state=42)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,source_file
746827,53,30767,2,2,70,102,35,35,35.0000,0.0000,51,51,51.0000,0.0000,5590.4053,130.0094,10255.6667,17758.1396,30761,3,3,3.0000,0.0000,3,3,3,3.0000,0.0000,3,3,0,0,0,0,40,80,65.0047,65.0047,35,51,41.4000,8.7636,76.8000,0,0,0,0,0,0,0,0,1,51.7500,35.0000,51.0000,40,0,0,0,0,0,0,2,70,2,102,-1,-1,1,20,0.0000,0.0000,0,0,0.0000,0.0000,0,0,BENIGN,Monday-WorkingHours
946912,53,48461,2,2,76,200,38,38,38.0000,0.0000,100,100,100.0000,0.0000,5695.3014,82.5406,16153.6667,27934.8124,48410,4,47,47.0000,0.0000,47,47,4,4.0000,0.0000,4,4,0,0,0,0,40,40,41.2703,41.2703,38,100,62.8000,33.9588,1153.2000,0,0,0,0,0,0,0,0,1,78.5000,38.0000,100.0000,40,0,0,0,0,0,0,2,76,2,200,-1,-1,1,20,0.0000,0.0000,0,0,0.0000,0.0000,0,0,BENIGN,Friday-WorkingHours-Morning
2216843,80,1,2,0,0,0,0,0,0.0000,0.0000,0,0,0.0000,0.0000,0.0000,2000000.0000,1.0000,0.0000,1,1,1,1.0000,0.0000,1,1,0,0.0000,0.0000,0,0,0,0,0,0,64,0,2000000.0000,0.0000,0,0,0.0000,0.0000,0.0000,0,0,0,0,1,0,0,0,0,0.0000,0.0000,0.0000,64,0,0,0,0,0,0,2,0,0,0,274,-1,0,32,0.0000,0.0000,0,0,0.0000,0.0000,0,0,DoS Hulk,Wednesday-workingHours
699389,53,191,2,2,74,138,37,37,37.0000,0.0000,69,69,69.0000,0.0000,1109947.6440,20942.4084,63.6667,27.1355,95,48,48,48.0000,0.0000,48,48,48,48.0000,0.0000,48,48,0,0,0,0,64,64,10471.2042,10471.2042,37,69,49.8000,17.5271,307.2000,0,0,0,0,0,0,0,0,1,62.2500,37.0000,69.0000,64,0,0,0,0,0,0,2,74,2,138,-1,-1,1,32,0.0000,0.0000,0,0,0.0000,0.0000,0,0,BENIGN,Monday-WorkingHours
1170268,2126,33,1,1,0,6,0,0,0.0000,0.0000,6,6,6.0000,0.0000,181818.1818,60606.0606,33.0000,0.0000,33,33,0,0.0000,0.0000,0,0,0,0.0000,0.0000,0,0,0,0,0,0,40,20,30303.0303,30303.0303,0,6,2.0000,3.4641,12.0000,0,0,0,1,0,0,0,0,1,3.0000,0.0000,6.0000,40,0,0,0,0,0,0,1,0,1,6,29200,0,0,40,0.0000,0.0000,0,0,0.0000,0.0000,0,0,PortScan,Friday-WorkingHours-Afternoon-PortScan
800686,44761,52,1,1,0,0,0,0,0.0000,0.0000,0,0,0.0000,0.0000,0.0000,38461.5385,52.0000,0.0000,52,52,0,0.0000,0.0000,0,0,0,0.0000,0.0000,0,0,0,0,0,0,32,32,19230.7692,19230.7692,0,0,0.0000,0.0000,0.0000,0,0,0,0,1,1,0,0,1,0.0000,0.0000,0.0000,32,0,0,0,0,0,0,1,0,1,0,122,683,0,32,0.0000,0.0000,0,0,0.0000,0.0000,0,0,BENIGN,Monday-WorkingHours
1434488,31843,4000835,1,4,1375,18,1375,1375,1375.0000,0.0000,6,0,4.5000,3.0000,348.1773,1.2497,1000208.7500,1980466.9050,3970854,1006,0,0.0000,0.0000,0,0,3998905,1332968.3330,2284513.0990,3970854,1006,1,0,0,0,20,92,0.2499,0.9998,0,1375,461.3333,707.7270,500877.4667,0,1,0,0,1,1,0,0,4,553.6000,1375.0000,4.5000,20,0,0,0,0,0,0,1,1375,4,18,229,0,0,20,0.0000,0.0000,0,0,0.0000,0.0000,0,0,BENIGN,Friday-WorkingHours-Afternoon-DDos
1968368,443,60397661,13,12,984,3402,596,0,75.6923,168.3743,1615,0,283.5000,590.5373,72.6187,0.4139,2516569.2080,4382604.5200,9993438,16,60400000,5033138.4170,5206470.2390,10100000,160,60300000,5482935.6360,5210736.8210,10100000,206,0,0,0,0,272,312,0.2152,0.1987,0,1615,168.6923,423.1000,179013.5815,0,0,0,1,0,0,0,0,0,175.4400,75.6923,283.5000,272,0,0,0,0,0,0,13,984,12,3402,8192,114,12,20,119347.1667,85254.7331,293371,84195,9946905.8330,109697.6633,9993438,9723071,BENIGN,Wednesday-workingHours
934343,443,263886,6,10,1091,4995,549,0,181.8333,226.0092,1460,0,499.5000,677.2740,23062.9893,60.6322,17592.4000,20036.2641,63073,4,229441,45888.2000,30589.7045,100064,25181,230623,25624.7778,34214.2325,96409,4,0,0,0,0,132,208,22.7371,37.8952,0,1460,358.0000,553.3024,306143.5000,0,0,0,1,0,0,0,0,1,380.3750,181.8333,499.5000,132,0,0,0,0,0,0,6,1091,10,4995,8192,5459,5,20,0.0000,0.0000,0,0,0.0000,0.0000,0,0,BENIGN,Friday-WorkingHours-Morning
693547,52676,36,1,1,6,6,6,6,6.0000,0.0000,6,6,6.0000,0.0000,333333.3333,55555.5556,36.0000,0.0000,36,36,0,0.0000,0.0000,0,0,0,0.0000,0.0000,0,0,0,0,0,0,20,20,27777.7778,27777.7778,6,6,6.0000,0.0000,0.0000,0,0,0,0,1,1,0,0,1,9.0000,6.0000,6.0000,20,0,0,0,0,0,0,1,6,1,6,119,255,0,20,0.0000,0.0000,0,0,0.0000,0.0000,0,0,BENIGN,Monday-WorkingHours

In [109]:
print(f"Dataset shape: {DATASET.shape}")
print(f"# rows: {DATASET.shape[0]}, # columns: {DATASET.shape[1]}\n")

COLS = DATASET.columns.tolist()

NUMERIC_COLS = DATASET.select_dtypes(include=[np.number]).columns.tolist()
print(f"# Numerical columns: {len(NUMERIC_COLS)}")

CATEGORICAL_COLS = DATASET.select_dtypes(include=['object']).columns.tolist()
print(f"# Categorical columns: {len(CATEGORICAL_COLS) - 1}")
for cols in CATEGORICAL_COLS:
    if cols != 'source_file':
        if cols == LABEL_COL and cols != 'source_file':
            print(f" - {cols} (target column)")
        else:
            print(f" - {cols}")

print(f"\nMemory usage: {DATASET.memory_usage(deep=True).sum() / (1024 * 1024):.2f} MB")

Dataset shape: (2830743, 80)
# rows: 2830743, # columns: 80

# Numerical columns: 78
# Categorical columns: 1
 - Label (target column)

Memory usage: 2040.29 MB

In [110]:
LABEL_COLS = DATASET[LABEL_COL].unique().tolist()
print(f"# Unique Label values: {len(LABEL_COLS)}")
for label in LABEL_COLS:
    print(f" - {label}")

# Unique Label values: 15
 - BENIGN
 - Infiltration
 - Bot
 - PortScan
 - DDoS
 - FTP-Patator
 - SSH-Patator
 - DoS slowloris
 - DoS Slowhttptest
 - DoS Hulk
 - DoS GoldenEye
 - Heartbleed
 - Web Attack � Brute Force
 - Web Attack � XSS
 - Web Attack � Sql Injection

## 1.3 Data Completeness and Integrity

### Checking Missing Values

In [111]:
nan_counts = df.isnull().sum()
nan_pct = df.isnull().mean() * 100

nan_df = pd.DataFrame({"NAN counts": nan_counts, "NAN %": nan_pct})
nan_df = nan_df[nan_df['NAN counts'] > 0].sort_values('NAN counts', ascending=False)

if nan_df.empty:
    print("\nNo missing values found in the dataset.")
else:
    print(f"# Columns with missing values: {nan_df.shape[0]}\n")
    display(nan_df)

# Columns with missing values: 1

              NAN counts  NAN %
Flow Bytes/s          20 0.0117

### Checking Infinite Values

In [112]:
inf_counts = df.isin([np.inf, -np.inf]).sum()
inf_pct = df.isin([np.inf, -np.inf]).mean() * 100

inf_df = pd.DataFrame({"Inf counts": inf_counts, "Inf %": inf_pct})
inf_df = inf_df[inf_df['Inf counts'] > 0].sort_values('Inf counts', ascending=False)

if inf_df.empty:
    print("\nNo infinite values found in the dataset.")
else:
    print(f"# Columns with infinite values: {inf_df.shape[0]}\n")
    display(inf_df)

# Columns with infinite values: 2

                Inf counts  Inf %
Flow Packets/s         135 0.0792
Flow Bytes/s           115 0.0675

### Checking Duplicate Values

In [113]:
n_dups = df.duplicated(keep='first').sum()
dup_pct = df.duplicated().mean() * 100

print(f'Total duplicate rows : {n_dups:,}')
print(f'Duplicate percentage  : {dup_pct:.2f}%')

dup_by_label = (
    df[df.duplicated(keep=False)]
    .groupby(LABEL_COL)
    .size()
    .sort_values(ascending=False)
    .rename('Dup Count')
)

print(f"\nDuplicate rows by label:\n{dup_by_label}")

Total duplicate rows : 6,066
Duplicate percentage  : 3.56%

Duplicate rows by label:
Label
BENIGN                      8779
Web Attack � Brute Force      62
Name: Dup Count, dtype: int64